#!/bin/bash
#SBATCH --job-name=train-steam-%j
#SBATCH --time=36:00:00
#SBATCH --output=/h/keenan/slurm_logs/%j-%N-output.out
#SBATCH --error=/h/keenan/slurm_logs/%j-%N-error.err
#SBATCH --open-mode=append
#SBATCH --partition=rtx6000
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=1
#SBATCH --mem=48G
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --qos=normal		# high, deadline
#SBATCH -N 1
#SBATCH --mail-type=ALL

. /h/keenan/pytorchenv
module use /pkgs/environment-modules/
#module load pytorch-36
nvidia-smi
python train.py #--pretrain /h/keenan/logs/2021-02-08/run4_aug10_cnn12_window3_res2592_nobundle/80000.pt
