#!/bin/bash
#SBATCH --job-name=run$1
#SBATCH --time=36:00:00
#SBATCH --output=/h/keenan/slurm_logs/%j-%N-output.out
#SBATCH --error=/h/keenan/slurm_logs/%j-%N-error.err
#SBATCH --open-mode=append
#SBATCH --partition=rtx6000	# p100, rtx6000, t4
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --qos=normal		# normal, high, deadline
#SBATCH -N 1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=keenburn2004@gmail.com

. /h/keenan/pytorchenv
module use /pkgs/environment-modules/
#module load pytorch-36
nvidia-smi
#python train.py #--pretrain /h/keenan/logs/2021-02-08/run4_aug10_cnn12_window3_res2592_nobundle/80000.pt
python train.py --config /h/keenan/RadarLocNet/config/run$1.json
